version: '3'

services:
    ros-tiago-base:
        build:
            context: .
        image: ros-tiago-base
        user: admin:1000
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities:
                            - gpu
        stdin_open: true
        tty: true
        privileged: true
        network_mode: "host"
        volumes:
            - \\wsl.localhost\Ubuntu-20.04\mnt\wslg:/tmp
        environment:
            - DISPLAY=:0
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        entrypoint: /usr/local/bin/scripts/workspace-entrypoint.sh
        command: tail -f /dev/null # bash -c "top"
